In [3]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=2)

# a)	Load the data in the file Iris.txt in a 2-D array called iris.

In [4]:
iris = np.genfromtxt('D:\Jupyter\IRIS.csv',delimiter="," ,dtype=str,skip_header=1)
iris

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1', '3.8', '1

# b)	Drop column whose index=4 from the array iris.

In [5]:
temp= np.delete(iris,4,1)
temp= temp.astype(float)
print(temp)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

# c)	Display the shape, dimensions and size of iris.

In [6]:
shape=iris.shape
dim=iris.ndim
size=iris.size
print("iris shape:\t",shape)
print("irs dimention :\t",dim)
print("iris size :\t",size)

iris shape:	 (150, 5)
irs dimention :	 2
iris size :	 750


# d)	Split iris into three 2-D arrays, each array for a different species.callthem iris1, iris2, and iris3.

In [7]:
idx1=iris[:,-1]=='Iris-setosa'
iris1=temp[idx1]

idx2=iris[:,-1]=='Iris-versicolor'
iris2=temp[idx2]

idx3=iris[:,-1]=='Iris-virginica'
iris3=temp[idx3]


# e)	Print the three arrays iris1,iris2,iris3

In [8]:
print("Iris 1 :")
print(iris1)
print("Iris 2 :")
print(iris3)
print("Iris 3 :")
print(iris3)

Iris 1 :
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]]
Iris 2 :
[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.

# f)	Create a 1-D array header having elements “sepal length”,” sepalwidth”, “petallength”, “petalwidth”,” species No” in that order.

In [9]:
header = np.array(["speal length", "sepal width", "petal length", "petal width", "Species No"])


# g)	Display the array header.

In [10]:
header

array(['speal length', 'sepal width', 'petal length', 'petal width',
       'Species No'], dtype='<U12')

# h)	Find the max, min, mean, and standard deviation for the columns of the iris and store the results in the arrays iris_max, iris_min, iris_avg, iris_std,iris_varresp.The results must be rounded to not more than two decimal places.

In [11]:
iris_max = np.round(np.max(temp.astype(float), axis=0), 2)
iris_min = np.round(np.min(temp, axis=0), 2)
iris_avg = np.round(np.mean(temp, axis=0), 2)
iris_std = np.round(np.std(temp, axis=0), 2)
iris_var = np.round(np.var(temp, axis=0), 2)

In [12]:
print(iris_max)

[7.9 4.4 6.9 2.5]


In [13]:
print(iris_min)

[4.3 2.  1.  0.1]


In [14]:
print(iris_avg)

[5.84 3.05 3.76 1.2 ]


In [15]:
print(iris_std)

[0.83 0.43 1.76 0.76]


In [16]:
print(iris_var)

[0.68 0.19 3.09 0.58]


# i)	Similarly find the max, min, mean, and standard deviation for the columns of the iris1, iris2, iris3 and store the results in the arrays with appropriate names

In [17]:
iris_max = np.round(np.max(iris1.astype(float), axis=0), 2)
iris1_min = np.round(np.min(iris1, axis=0), 2)
iris1_avg = np.round(np.mean(iris1, axis=0), 2)
iris_std = np.round(np.std(iris1, axis=0), 2)
iris_var = np.round(np.var(iris1, axis=0), 2)
print(iris_max)
print(iris1_min)
print(iris1_avg)
print(iris_std)
print(iris_var)

[5.8 4.4 1.9 0.6]
[4.3 2.3 1.  0.1]
[5.01 3.42 1.46 0.24]
[0.35 0.38 0.17 0.11]
[0.12 0.14 0.03 0.01]


In [18]:
iris_max = np.round(np.max(iris2.astype(float), axis=0), 2)
iris2_min = np.round(np.min(iris2, axis=0), 2)
iris2_avg = np.round(np.mean(iris2, axis=0), 2)
iris_std = np.round(np.std(iris2, axis=0), 2)
iris_var = np.round(np.var(iris2, axis=0), 2)
print(iris_max)
print(iris2_min)
print(iris2_avg)
print(iris_std)
print(iris_var)

[7.  3.4 5.1 1.8]
[4.9 2.  3.  1. ]
[5.94 2.77 4.26 1.33]
[0.51 0.31 0.47 0.2 ]
[0.26 0.1  0.22 0.04]


In [19]:
iris_max = np.round(np.max(iris3.astype(float), axis=0), 2)
iris3_min = np.round(np.min(iris3, axis=0), 2)
iris3_avg = np.round(np.mean(iris3, axis=0), 2)
iris_std = np.round(np.std(iris3, axis=0), 2)
iris_var = np.round(np.var(iris3, axis=0), 2)
print(iris_max)
print(iris3_min)
print(iris3_avg)
print(iris_std)
print(iris_var)

[7.9 3.8 6.9 2.5]
[4.9 2.2 4.5 1.4]
[6.59 2.97 5.55 2.03]
[0.63 0.32 0.55 0.27]
[0.4  0.1  0.3  0.07]


# j)	Check the minimum value for sepal length, sepal width , petal length, petal width of the three species in comparison to the minimum value of sepal length,sepalwidth,petallength,petal width for the data set as awhole and fill the table below with True if the species value is greater than the dataset value and False otherwise.
	Iris setosa	Iris virginica	Iris versicolor
Sepal length			
Sepal width			
Petal length			
Petal width			


In [20]:
check =[[]for i in range(len(header)-1)]
for i in range(len(check)):
    check[i].append(True if iris1_min[i] > iris_min[i] else False)
    check[i].append(True if iris2_min[i] > iris_min[i] else False)
    check[i].append(True if iris3_min[i] > iris_min[i] else False)
df = pd.DataFrame(check, columns=['Iris setosa', 'Iris virginica', 'Iris versicolor'], index=header[:-1])
df


Iris setosa  Iris virginica  Iris versicolor
speal length        False            True             True
sepal width          True           False             True
petal length        False            True             True
petal width         False            True             True

# k)	Compare Iris setosa’s average sepal width to that of Iris virginica.

In [37]:
one=iris1_avg[1]-iris3_avg[1]
if(one>=0):
    print(one,"setosa grater")
else:
    print(one,"virginica smaller")

0.44999999999999973 setosa grater


# l)	Compare Iris setosa’s average petallength to that of Iris virginica.

In [36]:
one=iris1_avg[2]-iris3_avg[2]
if(one >=0):
    print(one,"setosa grater")
else:
    print(one,"virginica Smaller")

-4.09 virginica grater


# m)	Compare Iris setosa’s average petal width to that of Iris virginica.

In [38]:
one=iris1_avg[3]-iris3_avg[3]
if(one >=0):
    print(one,"setosa grater")
else:
    print(one,"virginica Smaller")

-1.7899999999999998 virginica Smaller


# n)	Save the array iris_avg in a comma separated file named IrisMeanValues.txt on the hard disk.

In [39]:
np.savetxt('IrisMeanValues.txt', iris_avg, delimiter=',', fmt='%.2f')

# o)	Save the arrays irisw_max, iris_avg, iris_min in a comma separated file named IrisStat.txt on the hard disk.

In [40]:
iris_stat = np.vstack((iris_max, iris_avg, iris_min))
np.savetxt('IrisStat.txt', iris_stat, delimiter=', ', fmt='%.2f')  #np.savetxt(filename,values,delimiter,fmt)