# Numpy basics


In [1]:
import numpy as np

# a)	Create a one-dimensional array and perform  all operations on it.

In [2]:
#one-d array
arr=np.array([1,2,3,4,5])
print("Array elements are:",arr)
print("Array operations are:")
print("Addition :",arr+arr)
print("Subtraction :",arr-arr)
print("Multiplication :",arr*arr)
print("division : ",arr//arr)
print("Modules :",arr%arr)
print("Array sin :",np.sin(arr))
print("Sqrt root :",np.sqrt(arr))

Array elements are: [1 2 3 4 5]
Array operations are:
Addition : [ 2  4  6  8 10]
Subtraction : [0 0 0 0 0]
Multiplication : [ 1  4  9 16 25]
division :  [1 1 1 1 1]
Modules : [0 0 0 0 0]
Array sin : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Sqrt root : [1.         1.41421356 1.73205081 2.         2.23606798]


# b)	Create multi-dimensional arrays and find its shape and dimension 

In [3]:
arr =np.array([[1,2,3],[4,5,6]])
print("Array elements : ",arr) #printing array
print("Shape :",arr.shape) #printing shape
print("Dimention :",arr.ndim) #printing dimention

Array elements :  [[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Dimention : 2


# c)	Create a matrix full of zeros and ones 


In [4]:
arr = np.zeros((3,3))
print("Array full of zeros :",arr) #printing array zeros
arr = np.ones((3,3))
print("Array full of ones :",arr) #printing array ones

Array full of zeros : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array full of ones : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# d)	Reshape and flatten data in the array 

In [6]:
arr =np.array([[1,2,3],[4,5,6]])
print("Original array :",arr) #original array
print("Reshaped array :",arr.reshape(3,2)) #3x2 reshaped array
print("Flatten array :",arr.flatten()) #all elements to one-d array

Original array : [[1 2 3]
 [4 5 6]]
Reshaped array : [[1 2]
 [3 4]
 [5 6]]
Flatten array : [1 2 3 4 5 6]


# e)	Perform arithmetic operations on multi-dimensional  arrays

In [11]:
arr1=np.array([[1,2,3,],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print("array1 :\n",arr1)
print("array2 :\n",arr2)
print("Addition :\n",arr1+arr2)
print("Multiplication : \n",arr1*arr2)
print("Subtraction : \n",arr1-arr2)
print("division :\n",arr1/arr2)

array1 :
 [[1 2 3]
 [4 5 6]]
array2 :
 [[ 7  8  9]
 [10 11 12]]
Addition :
 [[ 8 10 12]
 [14 16 18]]
Multiplication : 
 [[ 7 16 27]
 [40 55 72]]
Subtraction : 
 [[-6 -6 -6]
 [-6 -6 -6]]
division :
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


# f)	Append data vertically and horizontally 

In [13]:
print("Vertical stack array :")
print(np.vstack((arr1,arr2)))
print("horizontal stack array :")
print(np.hstack((arr1,arr2)))

Vertical stack array :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
horizontal stack array :
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# g)	Apply indexing and slicing on array 

In [19]:
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
#indexing
print("Array indexing  : ",arr[1,2])
#slicing
print("Array slicing left:\n",arr[1:])
print("Array slicing right:\n",arr[:2])
print("Array subset :\n",arr[0:2,1:3])

Array indexing  :  6
Array slicing left:
 [[4 5 6]
 [7 8 9]]
Array slicing right:
 [[1 2 3]
 [4 5 6]]
Array subset :
 [[2 3]
 [5 6]]


# h)	Use statistical functions on array – Min, Max, Mean, Median and Standard Deviation 

In [21]:
print("Min function :\n",np.min(arr))
print("Max function :\n",np.max(arr))
print("Mean :\n",np.mean(arr))
print("Median :\n",np.median(arr))
print("Standard Deviation:\n",np.std(arr))

Min function :
 1
Max function :
 9
Mean :
 5.0
Median :
 5.0
Standard Deviation:
 2.581988897471611


# i)	Dot  matrix product of two arrays 

In [25]:
#dot product
arr1=np.array([[1,2,3,],[4,5,6],[7,8,9]])
arr2=np.array([[7,8,9],[10,11,12],[4,5,6]])
print("Matrix dot product :\n",np.dot(arr1,arr2))

Matrix dot product :
 [[ 39  45  51]
 [102 117 132]
 [165 189 213]]


# j)	Compute the Eigen values of a matrix 

In [28]:
matrix=np.array([[1,2],[3,4]])
eigenvalues=np.linalg.eigvals(matrix) #linalg means linear algebra
print("Eigen values :\n",eigenvalues)

Eigen values :
 [-0.37228132  5.37228132]


# k)	Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 

In [30]:
A=np.array([[3,1],[1,2]])
B=np.array([9,8])
solution=np.linalg.solve(A,B)
print("Solution of equations :")
print("x0 = ",solution[0])
print('x1 = ',solution[1])

Solution of equations :
x0 =  2.0
x1 =  3.0


# l)	Compute the multiplicative inverse of a matrix 

In [32]:
matrix=np.array([[4,7],[2,6]])
print("Matrix :\n",matrix)
print("Inverse Matrix :\n",np.linalg.inv(matrix))

Matrix :
 [[4 7]
 [2 6]]
Inverse Matrix :
 [[ 0.6 -0.7]
 [-0.2  0.4]]


# m)	Compute the rank of a matrix 

In [33]:
print("Matrix rank :\n",np.linalg.matrix_rank(matrix))

Matrix rank :
 2


# n) Compute the determinant of an array

In [34]:
print("Matrix determinant :\n",np.linalg.det(matrix))

Matrix determinant :
 10.000000000000002


# o)	Perform transpose and change of axes operations on arrays

In [38]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array Transpose :\n",arr.T)
print("Swap axes :\n",np.swapaxes(arr,0,1))

Array Transpose :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Swap axes :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


# p)	Perform splitting operations on arrays

In [42]:
import numpy as np

# Create a 2D array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Split the array horizontally into two parts
horizontally_split = np.hsplit(original_array, 2)

# Split the array vertically into three parts
vertically_split = np.vsplit(original_array, 3)

# Split the array at specified indices
custom_split = np.split(original_array, [1, 3], axis=1)

print("Original Array:")
print(original_array)

print("\nHorizontally Split Array:")
for part in horizontally_split:
    print(part)

print("\nVertically Split Array:")
for part in vertically_split:
    print(part)

print("\nCustom Split Array:")
for part in custom_split:
    print(part)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Horizontally Split Array:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]

Vertically Split Array:
[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]

Custom Split Array:
[[1]
 [5]
 [9]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 4]
 [ 8]
 [12]]
